shopping_proj/app/urls.py
from django.urls import path,re_path
from . import views


app_name = 'app'

urlpatterns = [
    path('',views.Home,name="home"),
    path('signup/',views.SignUpView,name="signup"),
    path('signin/',views.SignInView,name="signin"),
    path('signout/',views.SignOutView,name="signout"),
    path('search/',views.Search,name="search"),
    path('detail/<slug>/',views.Detail,name="detail"),
    path('api/products/', views.api_product, name="api_product"),
    path('categories/<slug>/', views.categories, name="categories"),
    path('<slug>/cart/', views.Cart, name="cart"),
    path('mycart/', views.MyCart, name="mycart"),
    path('api/products/', views.api_product, name="api_products"),
   # re_path('signup/',views.SignUpView,name=signup"")

]

shopping_proj/shopping_proj/urls.py
from django.conf.urls.static import static
from shopping_proj import settings
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('app.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopping_proj/app/models.py
from django.db import models
from autoslug import AutoSlugField
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator,MinValueValidator


class Category(models.Model):
    name = models.CharField(max_length=20,unique=True)
    slug = AutoSlugField(populate_from='name')
    image = models.ImageField(upload_to='categories',blank=True,null=True)
    description = models.TextField(blank=True)
    active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta():
        verbose_name_plural = 'Categories'

class Product(models.Model):
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    name = models.CharField(max_length=30,unique=True)
    slug = AutoSlugField(populate_from='name')
    image = models.ImageField(upload_to='product')
    brand = models.CharField(max_length=30)
    product_detail = models.TextField(blank=True,null=True)
    price = models.DecimalField(max_digits=15,decimal_places=2,default=0.0)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Review(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    ratings =  models.IntegerField(default=10,validators=[MaxValueValidator(10),MinValueValidator(1)])
    review = models.CharField(blank=True,max_length=100)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.review

shopping_proj/app/forms.py
from . import models
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User


class ReviewForm(forms.ModelForm):
    class Meta:
        model = models.Review
        fields = ['ratings','review']


class SignInForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

shopping_proj/app/views.py
from django.shortcuts import render,redirect
from django.urls import reverse_lazy
from . import models
from . import forms
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.db.models import Q
from .serializers import ProductSerialize
from rest_framework.decorators import api_view
from rest_framework.views import Response
from django.views import generic
from django.contrib.auth.decorators import login_required


def Home(request):
    products = models.Product.objects.filter(available=True)
    categories = models.Category.objects.filter(active=True)
    context = {"products": products, "categories": categories}
    return render(request, "app/home.html", context)


def Search(request):
    q = request.GET["q"]
    products = models.Product.objects.filter(available=True, name__icontains=q)
    categories = models.Category.objects.filter(active=True)
    context = {"products": products,
               "categories": categories,
               "title": q + " - search"}
    return render(request, "app/list.html", context)



def categories(request, slug):
    cat = models.Category.objects.get(slug=slug)
    products = models.Product.objects.filter(available=True, category=cat)
    categories = models.Category.objects.filter(active=True)
    context = {"products":products, "categories":categories, "title":cat.name + " - Categories"}
    return render(request, "app/list.html", context)

@login_required(login_url='app:signup')
def Detail(request, slug):
    product = models.Product.objects.get(available=True, slug=slug)
    if request.method == "POST":
        form = forms.ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.product = product
            review.user = request.user
            review.save()
            messages.success(request, "Review saved")
        else:
            messages.error(request, "Invalid form")
    else:
        form = forms.ReviewForm()


    categories = models.Category.objects.filter(active=True)
    context = {"product" : product,
               "categories":categories,
               "form": form}
    return render(request, "app/detail.html", context)

def Cart(request,slug):
    product = models.Product.objects.get(available=True,slug=slug)
    initial ={"item":[],"price":0.0,"count":0}
    session = request.session.get("data",initial)
    if slug in session["item"]:
        messages.success(request,"Already exists in cart!")
    else:
        session["item"].append(slug)
        session["price"]+=float(product.price)
        session["count"]+=1
        request.session["data"]=session
        messages.success(request,"Added Successfully!")
    return redirect('app:detail',slug)


def MyCart(request):
    sess = request.session.get("data", {"item":[]})
    products = models.Product.objects.filter(available=True, slug__in=sess["item"])
    categories = models.Category.objects.filter(active=True)
    context = {"products": products,
               "categories": categories,
               "title": "My Cart"}
    return render(request, "app/list.html", context)



def SignUpView(request):
    if request.method == "POST":
        form = forms.SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
            messages.success(request, "User saved")
            return redirect("app:signin")
        else:
            messages.error(request, "Error in form")
    else:
        form = forms.SignUpForm()
    context = {"form": form}
    return render(request, "app/signup.html", context)

def SignInView(request):
    if request.method == 'POST':
        form = forms.SignInForm(request.POST)
        if form.is_valid():
            username = form["username"].value()
            password = form["password"].value()
            user = authenticate(request,username=username,password=password)
            if user is not None:
                login(request,user)
                messages.success(request,'Successfully Logged In')
                return redirect('app:home')
            else:
                messages.warning(request,"Invalid Username or Password")
    else:
        form = forms.SignInForm()
    return render(request,'app/signin.html',{'form':form})

def SignOutView(request):
    logout(request)
    return redirect('app:signin')

@api_view(['GET'])
def api_product(request):
    query = request.GET.get('q','')
    product = models.Product.objects.filter(Q(name__icontains=query) | Q(product_detail__icontains=query))
    serialize = ProductSerialize(product,many=True)
    return Response(serialize.data)

shopping_proj/app/templates/app/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load bootstrap4 %}
<head>
    <meta charset="UTF-8">
    <title>BigCart</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- For Glyhicon -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'app/css/style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Cinzel&family=Julius+Sans+One&family=Merienda+One&family=Monoton&family=Quicksand&display=swap" rel="stylesheet">
</head>
<style>
    .side{
        position:relative;
        right:2%;
        display: flex;
        flex-direction: column;
        flex-wrap: wrap;
        justify-content: center;
        width: 150%;
        height: 100%;
        padding: 50px;
        border: 1px solid white;
        box-sizing: border-box;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
    }
    .content{
        position:relative;
        right:45%;
        display: flex;
        flex-direction: column;
        flex-wrap: wrap;
        justify-content: center;
        width: 150%;
        height: 100%;
        padding: 50px;
        border: 1px solid white;
        box-sizing: border-box;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
    }
    .brandname{
        font-family: 'Merienda One', cursive;
        color: white;
        text-shadow: 2px 2px 6px #000000;
    }
    .companyname{
 font-family: 'Merienda One', cursive;
         text-shadow: 2px 2px 9px red;
   }
   .t{
       font-family: 'Cinzel', serif;
       font-size:1em;
   }
   .x{
       font-family: 'Quicksand', sans-serif;
    }
    .k{
           font-family: 'Cinzel', serif;
           color: white;
        text-shadow: 2px 2px 3px #000000;}
</style>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
        <div class="container-fluid">
            <ul class="navbar-nav mr-auto">
                <li><a class="navbar-brand brandname" href="{% url 'app:home' %}">BigCart</a> </li>

            </ul>
            <ul class="nav navbar-nav">
                <li class="nav-item dropdown pr-3 k">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="fa fa-user-circle fa-lg" aria-hidden="true"> <small class="">{{request.user}}</small></span>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% if user.is_authenticated %}
                        <a class="dropdown-item" href="{% url 'app:signout' %}">SignOut</a>
                    {% else %}
                        <a class="dropdown-item" href="{% url 'app:signin' %}">SignIn</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'app:signup' %}">SignUp</a>
                    {% endif %}
                    </div>
                </li>
                 <li class="px-3"><a class="nav-item nav-link btn btn-outline-primary" href="{% url 'app:mycart' %}"><span class="fa fa-shopping-cart fa-lg" aria-hidden="true"></span> {{request.session.data.count}} Items</a> </li>
                <div class="px-4">
                <li>
                    <form class="form-inline my-2 my-lg-0" action="{% url 'app:search' %}">
                    <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </li>
                </div>
            </ul>
        </div>
    </nav>

    <div class="container-fluid ">
        <div class="">
        <div class="row justify-content-around">
            <div class="col-lg-3 pl-1 mt-2 ">
                <br>
                <div class="">
                <h1 class="companyname ">BigCart <span class="fa fa-shopping-cart fa-xl" aria-hidden="true"></span></h1>
                <ul class="list-group list-group-flush pt-4 ">
                    {% for c in categories %}
                    <a class="t list-group-item list-group-item-action" href="{% url 'app:categories' slug=c.slug %}">{{ c.name }}</a>
                    {% endfor %}
                </ul>
                </div>
            </div>

            <div class="col-lg-5 ml-5">
                <div class="">
                     {% bootstrap_messages %}
                </div>
                <div class="mt-3 content">
                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>
        </div>
    </div>
    <br>
</body>
</html>

shopping_proj/app/templates/app/detail.html
{% extends 'app/base.html' %}
{% load bootstrap4 %}
{% block content %}

    <div class="row x">
        <div class="col-md-8 ">

            <img src="/media/{{product.image}}" class="img-fluid">
        </div>
        <div class="col-md-4">
            <h3 class="my-3"><strong>{{product.name|title}}</strong></h3>
            <p>{{product.product_detail}}</p>
            <p><strong><em>“Success is the only thing <br>to change the behavior of others” </em></strong></p>
            <form action="{% url 'app:cart' product.slug %}">
                <input type="submit" class="btn btn-success btn-md text-center" value="Add to cart">
            </form>
        </div>
    </div>
    <br>
    <div class="row mb-5 x">
        <form method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-success">
        </form>
    </div>

    <div class="row x">
        <h4><strong>Customers Review</strong></h4>
        {% for review in product.review_set.all %}
            <div class="card mb-1 w-100">
                <div class="card-body">
                    <h6 class="card-title">Rate:<strong> {{review.ratings}}</strong></h6>
                    <h7 class="card-text">{{ review.review }}</h7>
                    <p class="card-text"><strong>By: {{ review.user.username }}</strong></p>
                </div>
                <div class="card-footer text-muted">
                    <small>{{ review.created|timesince }} ago</small>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

shopping_proj/app/templates/app/home.html
{% extends 'app/base.html' %}

{% block content %}

 <div class="row">
{% for item in products %}
    <div class="col-lg-4 col-md-6 mb-4 x">
              <div class="card h-100">
                <a href="#"><img class="card-img-top" src="/media/{{ item.image }}" alt=""></a>
                <div class="card-body">
                  <h4 class="card-title">
                    <a href="{% url "app:detail" item.slug %}">{{ item.name|title }}</a>
                  </h4>
                  <h5>Rs. {{ item.price|floatformat:"2" }}</h5>
                  <p class="card-text">{{ item.product_detail }}</p>
                </div>
                <div class="card-footer">
                  <small class="text-muted"><a class="btn btn-success" href="{% url 'app:cart' item.slug %}">Add to Cart</a></small>
                </div>
              </div>
            </div>
{% endfor %}
</div>
{% endblock %}

shopping_proj/app/templates/app/list.html
{% extends 'app/base.html' %}


{% block content %}
 <div class="row" x>
    {% for item in products %}
    <div class="col-lg-4 col-md-6 mb-4 ">
              <div class="card h-100">
                <a href="#"><img class="card-img-top" src="/media/{{ item.image }}" alt=""></a>
                <div class="card-body">
                  <h4 class="card-title">
                    <a href="{% url "app:detail" item.slug %}">{{ item.name|title }}</a>
                  </h4>
                  <h5>Rs. {{ item.price|floatformat:"2" }}</h5>
                  <p class="card-text">{{ item.product_detail }}</p>
                </div>
                <div class="card-footer">
                  <small class="text-muted"><a class="btn btn-success" href="{% url 'app:cart' item.slug %}">Add to Cart</a></small>
                </div>
              </div>
            </div>
     {% empty %}
        <div class="card w-100 mt-5 mr-2">
        <div class="card-body">
            <h3>Item not available</h3>
        </div>
        </div>
     {% endfor %}
</div>
{% endblock %}

shopping_proj/app/templates/app/signin.html
{% load bootstrap4 %}
{% load static %}
<style>
    .in{
         box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
         padding:20px 20px 20px 20px;
    }
</style>
<!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- For Glyhicon -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'app/css/style.css' %}">

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <ul class="navbar-nav mr-auto">
                <li><a class="navbar-brand brandname" href="{% url 'app:home' %}">BigCart</a> </li>
            </ul>
            <ul class="nav navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="fa fa-user-circle fa-lg" aria-hidden="true"></span>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% if user.is_authenticated %}
                        <a class="dropdown-item" href="{% url 'app:signout' %}">SignOut</a>
                    {% else %}
                        <a class="dropdown-item" href="{% url 'app:signin' %}">SignIn</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'app:signup' %}">SignUp</a>
                    {% endif %}
                    </div>
                </li>
                 <li class="px-3"><a class="nav-item nav-link btn btn-outline-primary" href="#"><span class="fa fa-shopping-cart fa-lg" aria-hidden="true"></span></a> </li>
                <div class="px-4">
                <li>
                    <form class="form-inline my-2 my-lg-0" action="{% url 'app:search' %}">
                    <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </li>
                </div>
            </ul>
        </div>
    </nav>
    <div class="container">
        {% bootstrap_messages %}
        <div class="col-md-6 offset-md-3 mt-5 in">
            <div class="card">
                <div class="card-header text-center">
                    Sign In
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        <input type="submit" class="btn btn-primary btn-lg text-center w-100 mb-3" value="SignIn">
                    </form>
                </div>
            </div>
        </div>
    </div>

shopping_proj/app/templates/app/signup.html
{% load bootstrap4 %}
{% load static %}
<style>
    .in{
         box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
         padding:20px 20px 20px 20px;
    }
</style>

<!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- For Glyhicon -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'app/css/style.css' %}">

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <ul class="navbar-nav mr-auto">
                <li><a class="navbar-brand brandname" href="{% url 'app:home' %}">BigCart</a> </li>
            </ul>
            <ul class="nav navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="fa fa-user-circle fa-lg" aria-hidden="true"></span>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% if user.is_authenticated %}
                        <a class="dropdown-item" href="{% url 'app:signout' %}">SignOut</a>
                    {% else %}
                        <a class="dropdown-item" href="{% url 'app:signin' %}">SignIn</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'app:signup' %}">SignUp</a>
                    {% endif %}
                    </div>
                </li>
                 <li class="px-3"><a class="nav-item nav-link btn btn-outline-primary" href="#"><span class="fa fa-shopping-cart fa-lg" aria-hidden="true"></span></a> </li>
                <div class="px-4">
                <li>
                    <form class="form-inline my-2 my-lg-0" action="{% url 'app:search' %}">
                    <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </li>
                </div>
            </ul>
        </div>
    </nav>

    <div class="container">
        {% bootstrap_messages %}
        <div class="col-md-6 offset-md-3 mt-5 in">
            <div class="card">
                <div class="card-header text-center">
                    Sign Up
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        <input type="submit" class="btn btn-primary btn-lg text-center w-100 mb-3" value="SignUp">
                    </form>
                </div>
            </div>
        </div>
    </div>

shopping_proj/app/templates/app/thanks.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>